## Global Alignment with Scoring Matrix 

Generalizing the Alignment Scoreclick to collapse
The edit alignment score in “Edit Distance Alignment” counted the total number of edit operations implied by an alignment; we could equivalently think of this scoring function as assigning a cost of 1 to each such operation. Another common scoring function awards matched symbols with 1 and penalizes substituted/inserted/deleted symbols equally by assigning each one a score of 0, so that the maximum score of an alignment becomes the length of a longest common subsequence of s
 and t
 (see “Finding a Shared Spliced Motif”). In general, the alignment score is simply a scoring function that assigns costs to edit operations encoded by the alignment.


One natural way of adding complexity to alignment scoring functions is by changing the alignment score based on which symbols are substituted; many methods have been proposed for doing this. Another way to do so is to vary the penalty assigned to the insertion or deletion of symbols.


In general, alignment scores can be either maximized or minimized depending on how scores are established. The general problem of optimizing a particular alignment score is called global alignment.


# Problem
To penalize symbol substitutions differently depending on which two symbols are involved in the substitution, we obtain a scoring matrix S
 in which Si,j
 represents the (negative) score assigned to a substitution of the i
th symbol of our alphabet A
 with the j
th symbol of A
.


A gap penalty is the component deducted from alignment score due to the presence of a gap. A gap penalty may be a function of the length of the gap; for example, a linear gap penalty is a constant g
 such that each inserted or deleted symbol is charged g
; as a result, the cost of a gap of length L
 is equal to gL
.


**Given:** Two protein strings s
 and t
 in FASTA format (each of length at most 1000 aa).

**Return:** The maximum alignment score between s
 and t
. Use:


The BLOSUM62 scoring matrix.
Linear gap penalty equal to 5 (i.e., a cost of -5 is assessed for each gap symbol).

Sample Dataset
>Rosalind_67
PLEASANTLY

>Rosalind_17
MEANLY

Sample Output
8

-M(L)EA--N-LY

In [1]:
-5+2+5+4-5-5+6-5+4+7


8

In [49]:
BL62 = '''X  A  C  D  E  F  G  H  I  K  L  M  N  P  Q  R  S  T  V  W  Y
A  4  0 -2 -1 -2  0 -2 -1 -1 -1 -1 -2 -1 -1 -1  1  0  0 -3 -2
C  0  9 -3 -4 -2 -3 -3 -1 -3 -1 -1 -3 -3 -3 -3 -1 -1 -1 -2 -2
D -2 -3  6  2 -3 -1 -1 -3 -1 -4 -3  1 -1  0 -2  0 -1 -3 -4 -3
E -1 -4  2  5 -3 -2  0 -3  1 -3 -2  0 -1  2  0  0 -1 -2 -3 -2
F -2 -2 -3 -3  6 -3 -1  0 -3  0  0 -3 -4 -3 -3 -2 -2 -1  1  3
G  0 -3 -1 -2 -3  6 -2 -4 -2 -4 -3  0 -2 -2 -2  0 -2 -3 -2 -3
H -2 -3 -1  0 -1 -2  8 -3 -1 -3 -2  1 -2  0  0 -1 -2 -3 -2  2
I -1 -1 -3 -3  0 -4 -3  4 -3  2  1 -3 -3 -3 -3 -2 -1  3 -3 -1
K -1 -3 -1  1 -3 -2 -1 -3  5 -2 -1  0 -1  1  2  0 -1 -2 -3 -2
L -1 -1 -4 -3  0 -4 -3  2 -2  4  2 -3 -3 -2 -2 -2 -1  1 -2 -1
M -1 -1 -3 -2  0 -3 -2  1 -1  2  5 -2 -2  0 -1 -1 -1  1 -1 -1
N -2 -3  1  0 -3  0  1 -3  0 -3 -2  6 -2  0  0  1  0 -3 -4 -2
P -1 -3 -1 -1 -4 -2 -2 -3 -1 -3 -2 -2  7 -1 -2 -1 -1 -2 -4 -3
Q -1 -3  0  2 -3 -2  0 -3  1 -2  0  0 -1  5  1  0 -1 -2 -2 -1
R -1 -3 -2  0 -3 -2  0 -3  2 -2 -1  0 -2  1  5 -1 -1 -3 -3 -2
S  1 -1  0  0 -2  0 -1 -2  0 -2 -1  1 -1  0 -1  4  1 -2 -3 -2
T  0 -1 -1 -1 -2 -2 -2 -1 -1 -1 -1  0 -1 -1 -1  1  5  0 -2 -2
V  0 -1 -3 -2 -1 -3 -3  3 -2  1  1 -3 -2 -2 -3 -2  0  4 -3 -1
W -3 -2 -4 -3  1 -2 -2 -3 -3 -2 -1 -4 -4 -2 -3 -3 -2 -3 11  2
Y -2 -2 -3 -2  3 -3  2 -1 -2 -1 -1 -2 -3 -1 -2 -2 -2 -1  2  7'''

BLOSUM62 = BL62.split('\n')
BLOSUM62 = [l.replace('  ', ' ').split(' ') for l in BLOSUM62]
print(BLOSUM62)
BLOSUM62DIC = {}
for i in range(1,len(BLOSUM62)):
    for j in range(1,len(BLOSUM62[i])):
        BLOSUM62DIC[BLOSUM62[0][i] + BLOSUM62[0][j]] = int(BLOSUM62[i][j])
print(BLOSUM62DIC)
print(len(BLOSUM62[0])) 
'''1-20'''
print(len(BLOSUM62[1][20])) 

[['X', 'A', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'K', 'L', 'M', 'N', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'Y'], ['A', '4', '0', '-2', '-1', '-2', '0', '-2', '-1', '-1', '-1', '-1', '-2', '-1', '-1', '-1', '1', '0', '0', '-3', '-2'], ['C', '0', '9', '-3', '-4', '-2', '-3', '-3', '-1', '-3', '-1', '-1', '-3', '-3', '-3', '-3', '-1', '-1', '-1', '-2', '-2'], ['D', '-2', '-3', '6', '2', '-3', '-1', '-1', '-3', '-1', '-4', '-3', '1', '-1', '0', '-2', '0', '-1', '-3', '-4', '-3'], ['E', '-1', '-4', '2', '5', '-3', '-2', '0', '-3', '1', '-3', '-2', '0', '-1', '2', '0', '0', '-1', '-2', '-3', '-2'], ['F', '-2', '-2', '-3', '-3', '6', '-3', '-1', '0', '-3', '0', '0', '-3', '-4', '-3', '-3', '-2', '-2', '-1', '1', '3'], ['G', '0', '-3', '-1', '-2', '-3', '6', '-2', '-4', '-2', '-4', '-3', '0', '-2', '-2', '-2', '0', '-2', '-3', '-2', '-3'], ['H', '-2', '-3', '-1', '0', '-1', '-2', '8', '-3', '-1', '-3', '-2', '1', '-2', '0', '0', '-1', '-2', '-3', '-2', '2'], ['I', '-1', '-1', '-3', '-3', '0', '-4',

In [58]:
def edit_alignment_sMD(m, v, w):
    '''Returns the edit score and edit alignment of strings v and w with global score matrix.'''
    import numpy as np

    # Initialize the matrices.
    S = np.zeros((len(v)+1, len(w)+1), dtype=int)
    backtrack = np.zeros((len(v)+1, len(w)+1), dtype=int)

    for i in range(1, len(v)+1):
        S[i][0] = i*(-5)
    for j in range(1, len(w)+1):
        S[0][j] = j*(-5)

    # Fill in the Score and Backtrack matrices according to score matrix m.
    for i in range(1, len(v)+1):
        for j in range(1, len(w)+1):
            #print(i,j)
            #print(m[v[i-1]+w[j-1]])
            scores = [S[i-1][j-1] + int(m[v[i-1]+w[j-1]]), #(m[v[i-1]+w[j-1]]
                      S[i-1][j]-5,                      #w.insert(j,'-') penalty of -5
                      S[i][j-1]-5]                      #v.insert(i,'-') penalty of -5
            S[i][j] = max(scores)
            backtrack[i][j] = np.argmax(scores) # scores.index(S[i][j]) 0,1,2
    print(S)
    print(backtrack)

    ## Quick lambda function to insert indels.
    #insert_indel = lambda word, i: word[:i] + '-' + word[i:]

    # Initialize the aligned strings as the input strings.
    v_aligned, w_aligned = v, w
    vl,wl = list(v_aligned),list(w_aligned)

    # Initialize the values of i,j and get the minimum score.
    i,j = len(v), len(w)
    max_score = S[i][j]

    # Backtrack to the edge of the matrix starting bottom right.
    while i*j != 0:
        if backtrack[i][j] == 1:
            i -= 1
            # w_aligned = insert_indel(w_aligned, j)
            wl.insert(j,'-')
            print('add - to l2 at ', j+1)
        elif backtrack[i][j] == 2:
            j -= 1
            # v_aligned = insert_indel(v_aligned, i)
            vl.insert(i,'-')            
            print('add - to l1 at ', i+1)
        else:
            i -= 1
            j -= 1

    # Prepend the necessary preceeding indels to get to (0,0).
    for _ in range(i):
        #w_aligned = insert_indel(w_aligned, 0)
        wl.insert(0,'-')
    for _ in range(j):
        #v_aligned = insert_indel(v_aligned, 0)
        vl.insert(0,'-')
    return str(max_score), ''.join(vl),''.join(wl) #v_aligned, w_aligned



input1 = '''PLEASANTLY'''
input2 = '''MEANLY'''
input1 = '''AQQKCKYWLQEPYHNQSTCIAFLNNAFRWHHNMRMYRMICTCRTYLEIEWDKRPYNRANG
FHSTGDCEFTNCPIHMYQANLWMQSNMFLGYRNFKAFSLKRTWFHKMARWRQKSDPCYRP
GPWCREQDNMLEVVACKPQLLEKIGIQKESFCGALGLRVILEARTHQIDQDWVEITCFAW
KKSRILRYDGCGVVMPTFNQQCIVHKHCYQDLNQDLEWSQRTERGKMNEGLRSVWWQRPF
HWTDPHCCSMTFNAQHVNNWAPGRECWKRYFMIGTQGHFIDFYMIPLERNDEHNRFALHD
TYAHYDGREWNFYYMSPPYPFWANTQCCDQTYMTGIGWESRTNTMGFPHCWVLIFLPLLS
RADNEWGIWYIHQCNSKAFQPTTYTKMQREFHVPVRTFHVFKNRPKCRQATEVLQFYRLL
YISKHHDMHADESRYCTLNTTVVSVYAGYEQCPWFEPWRSTGQQGYNDMHHCTHVCQAPK
KLFMKKAEWSDACMLKWIIKVIASAHSTSYRRPPTEDYMPINGPASCYCRIRWKCLSSGR
LSKQPWPPICHYFYWTSLSAIFVRNKYNYKSRHQFLDEWLDLVQMVCYKWEFRGNCDGCG
QGMGSSCPLYGPEYCDFTPNIVINGRRVSPCYCMLKQMDYWLSSQLFNTHNWTDKWIGEE
REHIANTHSLKWFTLTLGREYRKHLFVLDMDPLRMTKLVFCMTVILQFVRFCWIMLDHFF
LSNTWFAYLPKGFWIVEDLSVKTKKDVHPAQGTTTKLFFMFQQTPNQCWRISRSDSVVVK
KMQHCYTMNYPKASWWSDCACIAAHLIASSDLTRRDNLSKMCSINFNYWNDMPMYDRPAD
RRYWTCLDMPTDGGI'''

input2 = '''AQQKLEKRAMEINAFRWHHNMHMYRMICYNRALPWCFSGAHSTGDMKFTNCPIHMYQANL
WMQSNMTFLGNFHCMARWRQKSASKPHREQDNMLEVVACKPQQSSYSGTSILEIVIFYFA
QGIALGLTHQDWVEITCFLRYRGCGSVRMIMQSKWPGYYHKHDDGGSMNEGLRYVWNTTQ
SPSNWNRVHWTDPHSMMWPLQKFNNQAVGNTHRLNPGRECTKRKGMFGTQGRFIDCYMIC
LERNDVHNRFALHDSIYAHYDGYMSPPYEFWANTFTPEVRSCQQTYMTGIGWESRYNTMG
FPHYDWVLILLPALSRADNENSHQQSETSYTKMQREFHVWFVIYIIVRTKCRQATEVLQD
YRLLYIFFLEKENRYCTLNTRRSDKVVSWCDGHENGCMIAGYKQCPWFEPWRSTGQQGVH
CTHVTYTSKKKAEWYDACMLKLIIKVIASAHHKRLLWGSSYEQGIRPPTEDYMPINGIRW
KYRMPGRISWLSKQPWPPICSKFYWTSLSYIFKAAARNKYVSSHPGADMCHWWLDLVQMV
PFSWWKYLWVESAFCFRGNCDIWGQKFDMGKDMWWGSSCPLYGPEYCLFTPNIVINNRRV
SPCYTKLKQMDYWLSSQLFNKQNWIGEEEERIANWFTLTLGREYRKHLFVLDMDPLRMTK
AVFCITVILQFVRFCWIMLDFAHPLDPYFAYLPSFYCGFGIVEDLSVKTKKDVHPGGTLK
LFFMNLSQQTPNQCWRISRSDSVVVKTMHHIRVYYTRWKAAHIASSDLTLMDNLSKMCST
NFNYKNEEWYNDMPMYDRPADTCLDMPTDGAI
'''

input1 = input1.replace('\n','')
input2 = input2.replace('\n','')

'''# Get the edit alignment.
    edited = edit_alignment(input1, input2)

    # Print and save the answer.
    print ('\n'.join(edited))
    
     point = 0 
    trp = []
    for i in range(len(edited[-1])):
        if edited[-1][i] == '-':
            point -= 5
            trp.append(-5)
        else:
            if edited[-1][i] == edited[1][i]:
                for ci in range(1,len(BLOSUM62[0])):
                    if BLOSUM62[0][ci] == edited[1][i]:
                        point += int(BLOSUM62[ci][ci])
                        trp.append(int(BLOSUM62[ci][ci]))
                        
            else:
                for ci in range(1,len(BLOSUM62[0])):
                    if BLOSUM62[0][ci] == edited[1][i]:
                        for cj in range(1,len(BLOSUM62[ci])):
                            if BLOSUM62[0][cj] == edited[-1][i]:
                                point += int(BLOSUM62[ci][cj])
    print(point)'''
                        


"# Get the edit alignment.\n    edited = edit_alignment(input1, input2)\n\n    # Print and save the answer.\n    print ('\n'.join(edited))\n    \n     point = 0 \n    trp = []\n    for i in range(len(edited[-1])):\n        if edited[-1][i] == '-':\n            point -= 5\n            trp.append(-5)\n        else:\n            if edited[-1][i] == edited[1][i]:\n                for ci in range(1,len(BLOSUM62[0])):\n                    if BLOSUM62[0][ci] == edited[1][i]:\n                        point += int(BLOSUM62[ci][ci])\n                        trp.append(int(BLOSUM62[ci][ci]))\n                        \n            else:\n                for ci in range(1,len(BLOSUM62[0])):\n                    if BLOSUM62[0][ci] == edited[1][i]:\n                        for cj in range(1,len(BLOSUM62[ci])):\n                            if BLOSUM62[0][cj] == edited[-1][i]:\n                                point += int(BLOSUM62[ci][cj])\n    print(point)"

In [59]:
edited = edit_alignment_sMD(BLOSUM62DIC, input1, input2)
print('\n'.join(edited))


[[    0    -5   -10 ... -4050 -4055 -4060]
 [   -5     4    -1 ... -4041 -4046 -4051]
 [  -10    -1     9 ... -4031 -4036 -4041]
 ...
 [-4265 -4256 -4246 ...  2005  2000  1995]
 [-4270 -4261 -4251 ...  2000  2005  2000]
 [-4275 -4266 -4256 ...  1995  2000  2009]]
[[0 0 0 ... 0 0 0]
 [0 0 2 ... 2 0 2]
 [0 1 0 ... 2 2 2]
 ...
 [0 1 1 ... 0 2 2]
 [0 1 1 ... 0 0 2]
 [0 1 1 ... 1 1 0]]
add - to l2 at  802
add - to l2 at  802
add - to l2 at  802
add - to l2 at  802
add - to l1 at  830
add - to l1 at  829
add - to l1 at  829
add - to l1 at  829
add - to l1 at  829
add - to l2 at  763
add - to l2 at  760
add - to l2 at  760
add - to l2 at  760
add - to l2 at  760
add - to l2 at  760
add - to l2 at  758
add - to l2 at  758
add - to l2 at  758
add - to l2 at  751
add - to l1 at  762
add - to l1 at  761
add - to l2 at  718
add - to l2 at  717
add - to l1 at  732
add - to l1 at  732
add - to l1 at  732
add - to l2 at  635
add - to l2 at  635
add - to l2 at  635
add - to l2 at  635
add - to l2 at  