# 编写Markdown文件  
Markdown是一种轻量级标记语言，使用简单的语法即可快速编写结构化文档。以下是Markdown的基本用法和常见功能，帮助你快速上手。

## 1. 标题  

使用#表示标题，#的数量决定标题级别（1-6级）。 示例：  

> # 一级标题  
> ## 二级标题  
> ### 三级标题  
   
## 2. 字体  
  
斜体：用> * 或> _ 包裹文字，例如：*斜体*  
  
加粗：用> ** 或> __ 包裹文字，例如：**加粗**  
  
斜体加粗：用> *** 或> ___ 包裹文字，例如：> ***斜体加粗***  
  
## 3. 换行  
  
在一行末尾添加两个空格，或者插入一个空行即可换行。 示例：  
  
第一行内容  
第二行内容  
  
## 4. 列表  
  
无序列表：使用*、-或+  
   
有序列表：使用数字加. 示例：  
   
- 无序项1  
- 无序项2  
  
### 1. 有序项1  
### 2. 有序项2  
  
## 5. 链接与图片   
  
插入链接： [链接文本](链接地址) 示例：
  
[百度](https://www.baidu.com)  
插入图片： ![图片描述](图片地址) 示例：  
  
![示例图片](https://example.com/image.png)  

## 6. 引用  
  
使用>表示引用。可以嵌套多层引用。 示例：  
  
> 一级引用  
>> 二级引用  

## 7. 分割线  
  
使用**三个**或以上的-、*或下划线创建分割线。    
示例：  
  
---
## 8. 代码块
  
单行代码：用反引号> ` 包裹代码。示例:   `print("Hello World")`  
  
多行代码：用三个反引号包裹，并指定语言类型（如```python、bash```等）。 示例： 
   
```def hello():  print("Hello, Markdown!")```
  
## 9. 表格
  
使用竖线 >| 和横线 > - 创建表格。示例： 
  
| 项目 | 数量 | 单价 |  
| ------ | ---- | ---- |  
| 苹果 | 10 | $5 |  
| 香蕉 | 5 | $3 |  
Markdown语法简单易学，适用于笔记、博客、技术文档等场景。推荐使用编辑器如Typora或在线工具如Markdown在线编辑器进行实践！


PRETTY  
PRTTEIN

# 动态规划 > —— 编辑距离问题（又称Levenshtein距离） 
  
## 1. 背景  
编辑距离问题是一个经典的问题，用于量化两个字符串之间的差异，即将一个字符串转换成另一个字符串所需的最小编辑操作次数，包括插入、删除和替换字符。编辑距离广泛应用于自然语言处理、文本相似度检测、拼写检查、生物信息学等领域。 
   
## 2.  定义  
定义：给定两个字符串 s1 和 s2，计算将 s1 转换成 s2 所需的最少操作数。
  
本题： 
s1 = "pretty"  
s2 = "prttein"  
最少操作数为4（删除‘e’，替换 ‘y’ 为‘e’，插入‘i’，插入‘n’）。    
在编辑距离问题中，**状态转移方程**是用来描述如何从较小问题的解构建较大问题的解的数学表达式。它核心地指示了在动态规划表中如何更新每个单元格的值。 
   
## 3.状态转移方程
**状态定义**  
设 dp[i][j] 为从字符串 s1 的前 i 个字符转换到 s2 的前 j 个字符所需的最小编辑操作数。这里，s1[0..i-1] 和 s2[0..j-1] 分别表示字符串 s1 和 s2 的前 i 和 j 个字符。 

**状态转移方程的建立**  
考虑以下几种情况：  
  
### 1. 字符匹配（s1[i-1] == s2[j-1]）:   
如果当前两个字符相同，那么这一对字符不需要任何编辑操作。因此，当前问题的解可以直接继承前一个问题的解，即： 
[ dp[i][j] = dp[i-1][j-1] ]  
这表示我们不对这对字符进行任何编辑，直接继承左上角单元格的编辑操作数。 
  
### 2. 字符不匹配（s1[i-1] != s2[j-1]）:  
如果当前两个字符不相同，我们有三种策略来使得 s1[0..i-1] 转换为 s2[0..j-1]：  
**删除操作**：从 s1 中删除一个字符后，尝试匹配 s1[0..i-2] 至 s2[0..j-1]，操作数为 dp[i-1][j] + 1。  
**插入操作**：向 s1 中插入一个与 s2[j-1] 相同的字符，然后尝试匹配 s1[0..i-1] 至 s2[0..j-2]，操作数为 dp[i][j-1] + 1。 
**替换操作**：将 s1[i-1] 替换为与 s2[j-1] 相同的字符，然后匹配 s1[0..i-2] 至 s2[0..j-2]，操作数为 dp[i-1][j-1] + 1。 
综上，我们选择上述三种策略中的最小值：  
[ dp[i][j] = 1 + \min(dp[i-1][j], dp[i][j-1], dp[i-1][j-1]) ]   
  
**完整的状态转移方程**  

综合以上情况，编辑距离问题的状态转移方程可以表达为： 
![C:\Users\Hi\Downloads\动态规划状态转移方程.png](https://i-blog.csdnimg.cn/blog_migrate/b6afab0dff8edc50504589e07ba116ac.png)  

**边界条件**  
  
对于 i = 0 (即 s1 为空字符串时)，将 s2 的前 j 个字符全部插入到 s1 是唯一的选项，因此 dp[0][j] = j。  
对于 j = 0 (即 s2 为空字符串时)，将 s1 的前 i 个字符全部删除是唯一的选项，因此 dp[i][0] = i。  
通过上述状态转移方程，我们可以系统地填充整个动态规划表，并最终解决编辑距离问题。这种方法不仅确保了解的正确性，而且通过避免冗余计算，提高了效率。
  
## 4. 图解
**动态规划表初始化**： 
创建一个表格，其中行表示字符串 s1 的前 i 个字符，列表示字符串 s2 的前 j 个字符。我们使用一个 (len(s1)+1) x (len(s2)+1) 的表格，len(s1) 和 len(s2) 分别是两个字符串的长度。  
初始表格结构如下：

|   |   | P	| R	| T | T | E | I | N |  
|   | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 
| P	| 1	|  	|   |   |   |   |   |   |  	
| R	| 2	|  	|   |   |   |   |   |   |  	
| E | 3	|  	|   |   |   |   |   |   |  	
| T	| 4	|  	|   |   |   |   |   |   |  	
| T	| 5	|  	|   |   |   |   |   |   |  	
| Y	| 6	|  	|   |   |   |   |   |   |  	
  	
第一行 和 第一列 的填充是基于单字符插入和删除操作的累积成本。例如，第一行第二格的 1 表示将空串变为 “P” 需要一次插入操作，依此类推。
  
**填充过程**
遍历 s1 的每个字符（行），与 s2 的每个字符（列）进行比较：
  
### 1. P vs P:  
匹配。dp[0][0] + 0 = 0 （表示从"P"到"P"的最小编辑距离，无操作, 因为 “P” 匹配 “P”，dp[1][1]） 

### 2. P vs R:  
不匹配。取 1+min(左方, 上方, 左上方+1) = 1+min(0, 2, 1) = 1 (dp[1][2]表示从"P"到"R"的最小编辑距离经过"P"到"PR")  

### 3. P vs T:    
不匹配。1+min(1, 3, 2) = 2 (dp[1][3]表示由 “P” 到 “PRT”)  
  
### 4. P vs T:  
不匹配。1+min(2, 4, 3) = 3 (dp[1][4]表示由 “P” 到 “PRTT”)

### 5. P vs E:
不匹配。1+min(3, 5, 4) = 4 (dp[1][5]表示由 “P” 到 “PRTTE”)  

### 6. P vs I:
不匹配。1+min(4, 6, 5) = 5 (dp[1][5]表示由 “P” 到 “PRTTEI”)  

### 7. P vs N:
不匹配。1+min(5, 7, 6) = 6 (dp[1][5]表示由 “P” 到 “PRTTEIN”)  
  
继续填充表格（8-14，15-21，22-28，29-35，36-42）：
最后2行逐步分析与填充
T vs P, R, T， T， E， I， N:
### 29. T vs P:  
不匹配。1+min(5, 3, 4) = 4 (dp[5][1]表示由 “PRETT” 到“P”)  

### 30. T vs R:  
不匹配。1+min(4, 2, 3) = 3 (dp[5][2]表示由 “PRETT” 到“PR”)  

### 31. T vs T:   
匹配。dp[4][2] + 0 = 2 （表示从"PRETT"到"PRT"的最小编辑距离，无操作, 因为 “T” 匹配 “T”，dp[5][3]） 
  
### 32. T vs T:  
匹配。dp[4][3] + 0 = 1 （表示从"PRETT"到"PRTT"的最小编辑距离，无操作, 因为 “T” 匹配 “T”，dp[5][4]） 

### 33. T vs E:
不匹配。1+min(1, 2, 1) = 2 (dp[5][5]表示由 “PRETT” 到“PRTTE”,dp[5][4]+1或者dp[4][5]+1)   

### 34. T vs I:
不匹配。1+min(2, 3, 2) = 3 (dp[5][6]表示由 “PRETT” 到“PRTTEI”,dp[5][5]+1或者dp[4][6]+1)   

### 35. T vs N:
不匹配。1+min(3, 4, 3) = 4 (dp[5][7]表示由 “PRETT” 到“PRTTEIN”,dp[5][6]+1或者dp[4][7]+1) 

Final Row (Y):
类似上述步骤，我们继续用 s1 的 “Y” 与 s2 的每个字符进行比较填表。

Y vs P, R, T， T， E， I， N:
### 36. Y vs P:  
不匹配。1+min(6, 4, 5) = 4 (dp[6][1]表示由 “PRETTY” 到“P”)  

### 30. Y vs R:  
不匹配。1+min(5, 3, 4) = 4 (dp[6][2]表示由 “PRETTY” 到“PR”)  

### 31. Y vs T: 
不匹配。1+min(4, 2, 3) = 3 (dp[6][3]表示由 “PRETTY” 到“PRT”)    
  
### 32. Y vs T:  
不匹配。1+min(3, 1, 2) = 2 (dp[6][4]表示由 “PRETTY” 到“PRTT”)    

### 33. T vs E:
不匹配。1+min(2, 2, 1) = 2 (dp[6][5]表示由 “PRETTY” 到“PRTTE”)    

### 34. T vs I:
不匹配。1+min(2, 3, 2) = 3 (dp[6][6]表示由 “PRETTY” 到“PRTTEI”,dp[6][5]+1或者dp[5][6]+1)    

### 35. T vs N:
不匹配。1+min(3, 4, 3) = 4 (dp[6][7]表示由 “PRETT” 到“PRTTEIN”,dp[6][6]+1或者dp[6][7]+1) 
  
完整填充后的表格：  
|   |   | P | R | T | T | E | I | N |  
|   | 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 
| P	| 1 | 0 | 1 | 2 | 3 | 4 | 5 | 6 |  	
| R	| 2 | 1 | 0 | 1 | 2 | 3 | 4 | 5 |  	
| E | 3 | 2 | 1 | 1 | 1 | 2 | 3 | 4 | 	
| T	| 4 | 3 | 2 | 1 | 1 | 2 | 3 | 4 |  	
| T	| 5 | 4 | 3 | 2 | 1 | 2 | 3 | 4 |  	
| Y	| 6 | 5 | 4 | 3 | 2 | 2 | 3 | 4 | 
  
在最右下角的单元格 dp[6][7]，我们得到 s1 = "pretty" 和 s2 = "prttein" 的最小编辑距离为 4。这表明我们需要进行4次编辑操作（删除字符 ‘e’，并将一个 ‘y’ 替换为 ‘e’,添加字符 ‘i’和字符 ‘n’
或者添加字符 ‘e’，并将一个 ‘y’ 替换为 ‘e’,添加字符 ‘i’和字符 ‘n’
或者将一个 ‘e’ 替换为 ‘t’,将一个 ‘t’ 替换为 ‘e’,将一个 ‘y’ 替换为 ‘i’,添加字符 ‘n’）来将 “pretty”
回溯过程转换成 “prttein”。以下是更加具体的步骤和解释：

回溯过程
要详细了解如何从 “pretty” 变成 “prttein”，我们可以从填充完成的动态规划表格开始回溯。从表格的右下角 (dp[6][7]) 开始，每一步都选择了一个操作，直到我们回到表格的左上角 (dp[0][0])。

从表格回溯操作(1-3)：

0. 从 ‘y’ 到 ‘n’：
位置 (6, 7): 此时字符 ‘y’ (s1的第6个字符) 和 ‘n’ (s2的第7个字符) 不匹配。
可以通过将 ‘y’ 替换为 ‘n’ 来减少一个不匹配，即 dp[5][6]出发。所以我们进行替换操作。
或者可以通过添加 ‘n’ 来减少一个不匹配，即 dp[6][6]出发。所以我们进行添加操作。

01. dp[5][6]从 ‘t’ 到 ‘i’：
位置 (5, 6): 此时字符 ‘t’ (s1的第5个字符) 和 ‘i’ (s2的第6个字符) 不匹配。
可以通过将 ‘t’ 替换为 ‘i’ 来减少一个不匹配，即 dp[4][5]出发。所以我们进行替换操作。
或者可以通过添加 ‘i’ 来减少一个不匹配，即 dp[5][5]出发。所以我们进行添加操作。

011. dp[4][5]从 ‘t’ 到 ‘e’：
位置 (4, 5): 此时字符 ‘t’ (s1的第4个字符) 和 ‘e’ (s2的第5个字符) 不匹配。
可以通过将 ‘t’ 替换为 ‘e’ 来减少一个不匹配，即 dp[3][4]出发。所以我们进行替换操作。
或者可以通过添加 ‘e’ 来减少一个不匹配，即 dp[4][4]出发。所以我们进行添加操作。
  
0111. dp[3][4]从 ‘e’ 到 ‘t’：
位置 (3, 4): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第4个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][3]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][3]出发。所以我们进行添加操作。 

01111. dp[2][3]从 ‘r’ 到 ‘t’：
位置 (2, 3): 此时字符 ‘r’ (s1的第2个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过添加 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行添加操作。 
  
011111. dp[2][2]从 ‘r’ 到 ‘r’：
位置 (2, 2): 此时字符 ‘r’ (s1的第2个字符) 和 ‘r’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[1][1]，无需额外操作。

01112. dp[3][3]从 ‘e’ 到 ‘t’：
位置 (3, 3): 此时字符 ‘e’ (s1的第3个字符) 和 ‘tr’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][2]出发。所以我们进行添加操作。 

011121. dp[2][2]从 ‘r’ 到 ‘r’：
位置 (2, 2): 此时字符 ‘r’ (s1的第2个字符) 和 ‘r’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[1][1]，无需额外操作。
  
011122. dp[3][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘r’ (s2的第2个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘r’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行替换操作。
或者可以通过添加 ‘r’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。 
  
0111221. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。 
  
0111222. dp[3][1]从 ‘e’ 到 ‘p’：
位置 (3, 1): 此时字符 ‘e’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘e’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行添加操作。 

01112221. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。 

0112. dp[4][4]从 ‘t’ 到 ‘t’：
位置 (4, 4): 此时字符 ‘t’ (s1的第3个字符) 和 ‘t’ (s2的第4个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[3][3]，无需额外操作。

01121. dp[3][3]从 ‘e’ 到 ‘t’：
位置 (3, 3): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][2]出发。所以我们进行添加操作。 
  
011211. dp[2][2]从 ‘r’ 到 ‘r’：
位置 (2, 2): 此时字符 ‘r’ (s1的第2个字符) 和 ‘r’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[1][1]，无需额外操作。 
  
011212. dp[3][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。 

0112121. dp[2][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。  

0112122. dp[3][1]从 ‘e’ 到 ‘p’：
位置 (3, 1): 此时字符 ‘e’ (s1的第3个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘e’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行添加操作。

01121221. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。
  
012. dp[5][5]从 ‘t’ 到 ‘e’：
位置 (5, 5): 此时字符 ‘t’ (s1的第5个字符) 和 ‘e’ (s2的第5个字符) 不匹配。
可以通过将 ‘t’ 替换为 ‘e’ 来减少一个不匹配，即 dp[4][4]出发。所以我们进行替换操作。
或者可以通过添加 ‘e’ 来减少一个不匹配，即 dp[5][4]出发。所以我们进行添加操作。

0121. dp[4][4]从 ‘t’ 到 ‘t’：
位置 (4, 4): 此时字符 ‘t’ (s1的第2个字符) 和 ‘t’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[3][3]，无需额外操作。 
  
01211. dp[3][3]从 ‘e’ 到 ‘t’：
位置 (3, 3): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][2]出发。所以我们进行添加操作。 

011211. dp[2][2]从 ‘r’ 到 ‘r’：
位置 (2, 2): 此时字符 ‘r’ (s1的第2个字符) 和 ‘r’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[1][1]，无需额外操作。 
  
011212. dp[3][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。 

0112121. dp[2][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。  

0112122. dp[3][1]从 ‘e’ 到 ‘p’：
位置 (3, 1): 此时字符 ‘e’ (s1的第3个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘e’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行添加操作。

01121221. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。
  
0122. dp[5][4]从 ‘t’ 到 ‘t’：
位置 (5, 4): 此时字符 ‘t’ (s1的第2个字符) 和 ‘t’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[4][3]，无需额外操作。或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[4][4]出发。所以我们进行添加操作。   
    
01221. dp[4][3]从 ‘t’ 到 ‘t’：
位置 (4, 3): 此时字符 ‘t’ (s1的第4个字符) 和 ‘t’ (s2的第3个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[3][2]，无需额外操作。或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][3]出发。所以我们进行添加操作。  
  
012211. dp[3][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。 

0122111. dp[2][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。  

0122112. dp[3][1]从 ‘e’ 到 ‘p’：
位置 (3, 1): 此时字符 ‘e’ (s1的第3个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘e’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行添加操作。

0121121. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。

01222. dp[4][4]从 ‘t’ 到 ‘t’：
位置 (4, 4): 此时字符 ‘t’ (s1的第2个字符) 和 ‘t’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[3][3]，无需额外操作。 
  
012221. dp[3][3]从 ‘e’ 到 ‘t’：
位置 (3, 3): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][2]出发。所以我们进行添加操作。 

0122211. dp[2][2]从 ‘r’ 到 ‘r’：
位置 (2, 2): 此时字符 ‘r’ (s1的第2个字符) 和 ‘r’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[1][1]，无需额外操作。 
  
0122212. dp[3][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。 

01222121. dp[2][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。  

012221211. dp[3][1]从 ‘e’ 到 ‘p’：
位置 (3, 1): 此时字符 ‘e’ (s1的第3个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘e’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行添加操作。

0122212111. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。

02. dp[6][6]从 ‘y’ 到 ‘i’：
位置 (6, 6): 此时字符 ‘y’ (s1的第6个字符) 和 ‘i’ (s2的第6个字符) 不匹配。
可以通过将 ‘y’ 替换为 ‘i’ 来减少一个不匹配，即 dp[5][5]出发。所以我们进行替换操作。
或者可以通过添加 ‘i’ 来减少一个不匹配，即 dp[6][5]出发。所以我们进行添加操作。
  
021. dp[5][5]从 ‘t’ 到 ‘e’：
位置 (5, 5): 此时字符 ‘t’ (s1的第5个字符) 和 ‘e’ (s2的第5个字符) 不匹配。
可以通过将 ‘t’ 替换为 ‘e’ 来减少一个不匹配，即 dp[4][4]出发。所以我们进行替换操作。
或者可以通过添加 ‘e’ 来减少一个不匹配，即 dp[5][4]出发。所以我们进行添加操作。  
  
0212. dp[4][4]从 ‘t’ 到 ‘t’：
位置 (4, 4): 此时字符 ‘t’ (s1的第2个字符) 和 ‘t’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[3][3]，无需额外操作。 
  
02121. dp[3][3]从 ‘e’ 到 ‘t’：
位置 (3, 3): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][2]出发。所以我们进行添加操作。 

021211. dp[2][2]从 ‘r’ 到 ‘r’：
位置 (2, 2): 此时字符 ‘r’ (s1的第2个字符) 和 ‘r’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[1][1]，无需额外操作。 
  
021212. dp[3][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。 

0212121. dp[2][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。  

0212122. dp[3][1]从 ‘e’ 到 ‘p’：
位置 (3, 1): 此时字符 ‘e’ (s1的第3个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘e’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行添加操作。

02121221. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。

022. dp[6][5]从 ‘y’ 到 ‘e’：
位置 (6, 5): 此时字符 ‘y’ (s1的第6个字符) 和 ‘e’ (s2的第5个字符) 不匹配。
可以通过将 ‘y’ 替换为 ‘e’ 来减少一个不匹配，即 dp[5][4]出发。 
  
0221. dp[5][4]从 ‘t’ 到 ‘t’：
位置 (5, 4): 此时字符 ‘t’ (s1的第2个字符) 和 ‘t’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[4][3]，无需额外操作。或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[4][4]出发。所以我们进行添加操作。   
    
02211. dp[4][3]从 ‘t’ 到 ‘t’：
位置 (4, 3): 此时字符 ‘t’ (s1的第4个字符) 和 ‘t’ (s2的第3个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[3][2]，无需额外操作。或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][3]出发。所以我们进行添加操作。  
  
022111. dp[3][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。 

0221111. dp[2][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。  

0221112. dp[3][1]从 ‘e’ 到 ‘p’：
位置 (3, 1): 此时字符 ‘e’ (s1的第3个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘e’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行添加操作。

02211121. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。
  
02212. dp[4][4]从 ‘t’ 到 ‘t’：
位置 (4, 4): 此时字符 ‘t’ (s1的第2个字符) 和 ‘t’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[3][3]，无需额外操作。 
  
022121. dp[3][3]从 ‘e’ 到 ‘t’：
位置 (3, 3): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][2]出发。所以我们进行添加操作。 

0221211. dp[2][2]从 ‘r’ 到 ‘r’：
位置 (2, 2): 此时字符 ‘r’ (s1的第2个字符) 和 ‘r’ (s2的第2个字符) 匹配。
由于字符匹配，我们直接沿对角线向上移动到 dp[1][1]，无需额外操作。 
  
022122. dp[3][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[2][2]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。 

0221221. dp[2][2]从 ‘e’ 到 ‘r’：
位置 (3, 2): 此时字符 ‘e’ (s1的第3个字符) 和 ‘t’ (s2的第3个字符) 不匹配。
可以通过将 ‘e’ 替换为 ‘t’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行替换操作。
或者可以通过添加 ‘t’ 来减少一个不匹配，即 dp[3][1]出发。所以我们进行添加操作。  

0221222. dp[3][1]从 ‘e’ 到 ‘p’：
位置 (3, 1): 此时字符 ‘e’ (s1的第3个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘e’ 来减少一个不匹配，即 dp[2][1]出发。所以我们进行添加操作。

02212221. dp[2][1]从 ‘r’ 到 ‘p’：
位置 (2, 1): 此时字符 ‘r’ (s1的第2个字符) 和 ‘p’ (s2的第1个字符) 不匹配。
可以通过添加 ‘r’ 来减少一个不匹配，即 dp[1][1]出发。所以我们进行添加操作。

从 ‘p’ 到 ‘’ (空)：
位置 (1, 0): 最后，删除 ‘p’，即 dp[0][0]出发
从  ‘’ (空) 到 ‘p’：
位置 (0, 1): 最后，删除 ‘p’, 即 dp[0][0]出发

完成所有转换。
结果
通过以上回溯步骤，我们可以确定将 “pretty” 转换为 “prttein” 的最小编辑操作序列是：

删除字符 ‘e’，‘y’ 替换为 ‘e’,插入字符 ‘i’和字符 ‘n’
或者插入字符 ‘e’，‘e’ 替换为 ‘y’,插入字符 ‘i’和字符 ‘n’
或者‘e’ 替换为 ‘t’,‘t’ 替换为 ‘e’,‘y’ 替换为 ‘i’,插入字符 ‘n’
  
## 5. 复杂度分析  
**时间复杂度**：O(mn)，因为需要填充一个 m x n 的矩阵。  
**空间复杂度**：O(mn)，可以优化到 O(min(m, n)) 通过只保留当前和前一行的状态。
为了清晰地解释编辑距离问题的动态规划解法，并辅以图解，我们可以使用一个示例和配套的表格。我们将采用简单的字符串 s1 = "horse" 和 s2 = "ros" 来阐述过程。


In [243]:

## 6. 实现00

In [83]:
import numpy as np
def edit_distance(s1,s2):
    """
    计算两个字符串s1和s2之间的最小编辑距离。
    最小编辑距离是将s1转换成s2所需的最少单字符编辑操作次数（插入、删除、替换）。
    相当于可以同步对s1，s2做插入、替换而已 
    
    参数:
    s1 (str): 源字符串。
    s2 (str): 目标字符串。
    
    m为s1的长度，n为s2的长度：m<n则插入在s1，向下操作(否则改变)，大于则插入在s2，向右操作（否则改变）

    返回:
    dp[m][n](int): s1转换成s2的最小编辑距离。
    """
    copy1 = list(s1)
    copy2 = list(s2)
    m, n = len(s1), len(s2)
    # 创建一个二维数组dp，m+1行n+1列
    dp = [[0] * (n+1) for _ in range(m+1)]

    # 初始化dp数组的第一行和第一列
    for i in range(m+1):
        dp[i][0] = i  # 将s1的前i个字符删除
    for j in range(n+1):
        dp[0][j] = j  # 将s2的前j个字符插入到s1中

    # 填充dp数组的其余部分
    for i in range(1, m + 1):
        for j in range(1, n + 1):
            if s1[i - 1] == s2[j - 1]:
                dp[i][j] = dp[i - 1][j - 1]  # 字符相同，无需编辑
            else:
                operation = [dp[i - 1][j],    # 删除操作（等同于对s2进行插入）
                             dp[i][j - 1],     # 插入操作
                             dp[i - 1][j - 1]] # 替换操作
                dp[i][j] = 1 + min(operation)
    return [dp[m][n],dp]  # 返回将整个s1转换成s2的最小编辑距离


In [84]:
# 示例使用
s1 = "horse"
s2 = "ros"
print("最小编辑距离:", edit_distance(s1,s2)[0])
DP = edit_distance(s1,s2)[1]
print("动态规划矩阵：\n",np.array(DP).reshape(len(s1)+1,len(s2)+1))


最小编辑距离: 3
动态规划矩阵：
 [[0 1 2 3]
 [1 1 2 3]
 [2 2 1 2]
 [3 2 2 2]
 [4 3 3 2]
 [5 4 4 3]]


In [85]:
s1 = "pretty"
s2 = "prttein"
print("最小编辑距离:", edit_distance(s1,s2)[0])
DP = edit_distance(s1,s2)[1]
print("动态规划矩阵：\n",np.array(DP).reshape(len(s1)+1,len(s2)+1))

最小编辑距离: 4
动态规划矩阵：
 [[0 1 2 3 4 5 6 7]
 [1 0 1 2 3 4 5 6]
 [2 1 0 1 2 3 4 5]
 [3 2 1 1 2 2 3 4]
 [4 3 2 1 1 2 3 4]
 [5 4 3 2 1 2 3 4]
 [6 5 4 3 2 2 3 4]]


In [4]:
s1 ="LRTNLPVYLYNWVKIDVYHHTGAKFPYLKEEAQCRNRNPNQCYHRAISHGGTHPFRTTHMYDENRMHTIIHNNCWAKTRQWFKPETYLWVQAWNKIIPWTKKELEMQWKDIGLPFGPPKIFSFFPRWITMYVTTEINCLDGNYGQNKLMNPTPAEWCPPIFRLMPINVQRSPLVTMRCWDTHDMANLNRIMVSKLVHSISMTQKVFKCMLPLTTQTECCYRPESQEYNKMQAKYNMEANGSSMATQKVRRKWDDTSCYQHFEVCGKIQCAYDVSVSSIPFPEWRFNGEWIVGWDENNHPFMKFHLTHYKTGACLQGQKWSIAPATYASCGRENEAGGMQFIASRLAFRFTGRETTFVRDFGACYRQAKIHAVIIYEYSGILRDVSQMRDGDFFTSHSMKYKAYHRDRMLQEWVMHGRMSTPGQNFHGKEPSSVNEMSKQKYANCPWFWNAEVLFMGCFFTWWPFHKVIPSGDSQDDRCLEGDWCKVIPEVSSKAGWWHRTTMWMTAEPCKMFALFKYVKPEEANSFAPSQDVFACPFVNVTIFMKKFFYKDFIVCDLMDDTQSGMHKTGRFKAFFCHHDNKYGTLSMHSMFIRAQFWHGHWIDTSGRTRNSMTGNWWFTHKYFKSMNRCGHAGECPIPEVPDHDYPVRHICYWQKRLKEVYDPPGEGQIQPIVFRGWYYYFRIGSSDGFYSHCITKVNKFRSKLRYWGKLHLTQAFEADMWCAEMCENLKAWDKHPVFTRWCSESRPHMTDQSTLA"
s2 = "LRTNLPVYVYHHTPCKDQNCVQTKMEAQRINCQMHVMKNWQHRAISHGMHHNQCWAKTRQWEKPETYLWQQPQAWSTRRPPNEIIPSHKKELEMQWKDIVLPFGPPKIFSFFPRWITRTLDYQMNNCLDGNYGQMKLMLFPTPGQDGTVEWPPIFRIMPINVTGAMARSPLLTMRCWDTPQQMVSKLVHSISMTQKVFKCMLPLTTQYCGQYTPTWAYACDCIYRPESQHYNSMQAKMLTDPPENNEANGSSMATQKCRHKWDDTSCYQFFFVCGKIAAIEEHRVAHDVSIFHPSSIPFPEWRFNGENEIVGWDENNHPFMKTHYTWREYRYKTRAWLQGAETQLGTTATYVDNGISHACGRCNSAGGMQFIRSRLAFRFTRKDCGSREVRDFGACYRQAKIIMIAIRWVIYEIWRDVSQMRDGSFFTSHCTRETWTTYKAYHRDQEWVGYEVSYHGRMSTPGENFHGPEPSSIRWMATCNEMSCNAEVLTCNTCHIKAHGCFFCNRGKVCSGCYQLGRFNITQDDRCPEVSSWHRTTMWMTAEPCKMFALFKYVKPEEANSFAQDVFVCPFKKFFYKDFIFCDLDDTQSCHMHKTGRFKAFQRECHEVKEQDDNKYGTLSFFIRFWHGHWGRNKFDCDWDRINLWNCPLTSIAQYMTGNWKFTQKYFKRMNRCVHASGVPWLQLPEVPDHDYPVVCISDRMDHNCYNQKRLKPVYDPPGENPFWMRGFMSRRWRDCWFTHPVAYTYSYIALNRSSDGRYSHCIKLRYWGKMPHLRWAFEADMTDIFCAEMCENLKAWDKHPDMSTHIVLMHTHA"
DP = edit_distance(s1,s2)[1]
print("最小编辑距离:", edit_distance(s1,s2)[0])
print("动态规划矩阵：\n",np.array(DP).reshape(len(s1)+1,len(s2)+1))

最小编辑距离: 385
动态规划矩阵：
 [[  0   1   2 ... 813 814 815]
 [  1   0   1 ... 812 813 814]
 [  2   1   0 ... 811 812 813]
 ...
 [754 753 752 ... 384 385 385]
 [755 754 753 ... 385 385 386]
 [756 755 754 ... 386 386 385]]


In [4]:
import numpy as np

def edit_distance_allignment(s1,s2,dp):
    """
    计算两个字符串s1和s2之间的最小编辑距离。
    最小编辑距离是将s1转换成s2所需的最少单字符编辑操作次数（插入、删除、替换）。
    相当于可以同步对s1，s2做插入、替换而已 
    
    参数:
    s1 (str): 源字符串。
    s2 (str): 目标字符串。
    
    m为s1的长度，n为s2的长度：m<n则插入在s1，向下操作(否则改变），大于则插入在s2，向右操作（否则改变）

    返回:
    dp[m][n](int): s1转换成s2的最小编辑距离。
    """
    m, n = len(s1), len(s2)
    # 倒回
    print('backtrade')
    copy11 = list(s1)
    copy22 = list(s2)  
    flag = 1
    for p in range(1,m+1):
        if flag:    
            ENDQ = 1 
        else:
            ENDQ = Q
        for q in range(ENDQ,n+1):
                if copy11[m-p] == copy22[n-q]:
                    print('cp1 at:',m-p,copy11[m-p],'identical to','cp2 at:',n-q,copy22[n-q])
                    Q = q + 1
                    flag = 0
                    break
                elif copy11[m-p] != copy22[n-q]:
                    backtr = [dp[m-p][n+1-q],    # 删除操作（等同于对s2进行插入）
                            dp[m+1-p][n-q],     # 插入操作
                            dp[m-p][n-q]] # 替换操作
                    #dp[i][j] = 1 + min(operation)
                    print(m-p,n-q,backtr,p,q,m,n,copy11,copy22)
                   # if m < n and m-p == m-1 and m-p < n-q:
                   #     print('add - to cp1 at :',m+1-p)
                   # #   copy11.pop(0)
                   #     copy11.insert(m+1-p,'-')

                   # if m > n and n-q == n-1 and m-p > n-q:
                   #     print('add - to cp2 at:',n+1-q)
                   # #   copy22.pop(0)
                   #     copy22.insert(n+1-q,'-') 
                   #     Q = q
                   #     flag = 0
                   #     break 
                    
                    print(copy11,copy22,'pre')                   
                    
                    if dp[m-p][n-q] >= dp[m-p][n+1-q] and dp[m+1-p][n-q] >= dp[m-p][n+1-q]:     
                        if m-p > n-q:
                            print('add - to cp2:',n+1-q)
                            #copy22.pop(0)
                            copy22.insert(n+1-q,'-')
                            print(copy11,copy22,'after add - to cp2')  
                            Q = q
                        else:
                            print('edit cp1 at:',m-p,copy11[m-p],'to cp2 at ',n-q,copy22[n-q])
                            copy11[m-p] = copy22[n-q]
                            print(copy11,copy22,'after edit cp1')  
                            Q = q + 1
                        flag = 0
                        break  
                   
                    elif dp[m-p][n-q] >= dp[m+1-p][n-q] and dp[m-p][n+1-q] >= dp[m+1-p][n-q]:
                        if m-p < n-q :
                            print('add - to cp1:',m+1-p)
                            ##copy11.pop(0)
                            copy11.insert(m+1-p,'-')
                            print(copy11,copy22,'after add - to cp1')  
                        else:
                            print('edit cp1 at:',m-p,copy11[m-p],'to cp2 at ',n-q,copy22[n-q])
                            copy11[m-p] = copy22[n-q]
                            print(copy11,copy22,'after change')  
                            Q = q + 1
                            flag = 0
                            break 

                    elif dp[m-p][n+1-q] >= dp[m-p][n-q] and dp[m+1-p][n-q] >= dp[m-p][n-q]:
                        print('edit cp1 at:',m-p,copy11[m-p],'to cp2 at ',n-q,copy22[n-q])
                        copy11[m-p] = copy22[n-q]
                        print(copy11,copy22,'after change')  
                        Q = q + 1
                        flag = 0
                        break  

    return [copy11,copy22]  # 返回将整个s1转换成s2的最小编辑距离


In [5]:
# 示例使用
s1 = "horse"
s2 = "ros"
DP = edit_distance(s1,s2)[1]
print("Alignment后的字符串:", edit_distance_allignment(s1,s2,DP)[0], edit_distance_allignment(s1,s2,DP)[1])


backtrade
4 2 [2, 4, 3] 1 1 5 3 ['h', 'o', 'r', 's', 'e'] ['r', 'o', 's']
['h', 'o', 'r', 's', 'e'] ['r', 'o', 's'] pre
add - to cp2: 3
['h', 'o', 'r', 's', 'e'] ['r', 'o', 's', '-'] after add - to cp2
cp1 at: 3 s identical to cp2 at: 2 s
2 1 [1, 2, 2] 3 2 5 3 ['h', 'o', 'r', 's', 'e'] ['r', 'o', 's', '-']
['h', 'o', 'r', 's', 'e'] ['r', 'o', 's', '-'] pre
add - to cp2: 2
['h', 'o', 'r', 's', 'e'] ['r', 'o', '-', 's', '-'] after add - to cp2
cp1 at: 1 o identical to cp2 at: 1 o
0 0 [1, 1, 0] 5 3 5 3 ['h', 'o', 'r', 's', 'e'] ['r', 'o', '-', 's', '-']
['h', 'o', 'r', 's', 'e'] ['r', 'o', '-', 's', '-'] pre
edit cp1 at: 0 h to cp2 at  0 r
['r', 'o', 'r', 's', 'e'] ['r', 'o', '-', 's', '-'] after change
backtrade
4 2 [2, 4, 3] 1 1 5 3 ['h', 'o', 'r', 's', 'e'] ['r', 'o', 's']
['h', 'o', 'r', 's', 'e'] ['r', 'o', 's'] pre
add - to cp2: 3
['h', 'o', 'r', 's', 'e'] ['r', 'o', 's', '-'] after add - to cp2
cp1 at: 3 s identical to cp2 at: 2 s
2 1 [1, 2, 2] 3 2 5 3 ['h', 'o', 'r', 's', 'e'] ['r

In [6]:
s1 = "pretty"
s2 = "prttein"
DP = edit_distance(s1,s2)[1]
print("Alignment后的字符串:", edit_distance_allignment(s1,s2,DP)[0], edit_distance_allignment(s1,s2,DP)[1])

backtrade
5 6 [4, 3, 3] 1 1 6 7 ['p', 'r', 'e', 't', 't', 'y'] ['p', 'r', 't', 't', 'e', 'i', 'n']
['p', 'r', 'e', 't', 't', 'y'] ['p', 'r', 't', 't', 'e', 'i', 'n'] pre
add - to cp1: 6
['p', 'r', 'e', 't', 't', 'y', '-'] ['p', 'r', 't', 't', 'e', 'i', 'n'] after add - to cp1
5 5 [3, 2, 2] 1 2 6 7 ['p', 'r', 'e', 't', 't', 'y', '-'] ['p', 'r', 't', 't', 'e', 'i', 'n']
['p', 'r', 'e', 't', 't', 'y', '-'] ['p', 'r', 't', 't', 'e', 'i', 'n'] pre
edit cp1 at: 5 y to cp2 at  5 i
['p', 'r', 'e', 't', 't', 'i', '-'] ['p', 'r', 't', 't', 'e', 'i', 'n'] after change
4 4 [2, 1, 1] 2 3 6 7 ['p', 'r', 'e', 't', 't', 'i', '-'] ['p', 'r', 't', 't', 'e', 'i', 'n']
['p', 'r', 'e', 't', 't', 'i', '-'] ['p', 'r', 't', 't', 'e', 'i', 'n'] pre
edit cp1 at: 4 t to cp2 at  4 e
['p', 'r', 'e', 't', 'e', 'i', '-'] ['p', 'r', 't', 't', 'e', 'i', 'n'] after change
cp1 at: 3 t identical to cp2 at: 3 t
2 2 [1, 1, 0] 4 5 6 7 ['p', 'r', 'e', 't', 'e', 'i', '-'] ['p', 'r', 't', 't', 'e', 'i', 'n']
['p', 'r', 'e', 't

In [7]:
import numpy as np

def edit_distance_allignment(s1,s2,dp):
    """
    计算两个字符串s1和s2之间的最小编辑距离。
    最小编辑距离是将s1转换成s2所需的最少单字符编辑操作次数（插入、删除、替换）。
    相当于可以同步对s1，s2做插入、替换而已 
    
    参数:
    s1 (str): 源字符串。
    s2 (str): 目标字符串。
    
    m为s1的长度，n为s2的长度：m<n则插入在s1，向下操作(否则改变），大于则插入在s2，向右操作（否则改变）

    返回:
    dp[m][n](int): s1转换成s2的最小编辑距离。
    """
    m, n = len(s1), len(s2)
    # 倒回
    copy11 = list(s1)
    copy22 = list(s2)  
    flag = 1
    for p in range(1,m+1):
        if flag:    
            ENDQ = 1 
        else:
            ENDQ = Q
        for q in range(ENDQ,n+1):
                if copy11[m-p] == copy22[n-q]:
#                    print('cp1 at:',m-p,copy11[m-p],'identical to','cp2 at:',n-q,copy22[n-q])
                    Q = q + 1
                    flag = 0
                    break
                elif copy11[m-p] != copy22[n-q]:
                    backtr = [dp[m-p][n+1-q],    # 删除操作（等同于对s2进行插入）
                            dp[m+1-p][n-q],     # 插入操作
                            dp[m-p][n-q]] # 替换操作
                    #dp[i][j] = 1 + min(operation)
#                    print(m-p,n-q,backtr,p,q,m,n,copy11,copy22)
                   # if m < n and m-p == m-1 and m-p < n-q:
                   #     print('add - to cp1 at :',m+1-p)
                   # #   copy11.pop(0)
                   #     copy11.insert(m+1-p,'-')

                   # if m > n and n-q == n-1 and m-p > n-q:
#                   #     print('add - to cp2 at:',n+1-q)
                   # #   copy22.pop(0)
                   #     copy22.insert(n+1-q,'-') 
                   #     Q = q
                   #     flag = 0
                   #     break 
                    
#                    print(copy11,copy22,'pre')                   
                    
                    if dp[m-p][n-q] >= dp[m-p][n+1-q] and dp[m+1-p][n-q] >= dp[m-p][n+1-q]:     
                        if m-p > n-q:
#                            print('add - to cp2:',n+1-q)
                            #copy22.pop(0)
                            copy22.insert(n+1-q,'-')
#                            print(copy11,copy22,'after add - to cp2')  
                            Q = q
                        else:
#                            print('edit cp1 at:',m-p,copy11[m-p],'to cp2 at ',n-q,copy22[n-q])
                            copy11[m-p] = copy22[n-q]
#                            print(copy11,copy22,'after edit cp1')  
                            Q = q + 1
                        flag = 0
                        break  
                   
                    elif dp[m-p][n-q] >= dp[m+1-p][n-q] and dp[m-p][n+1-q] >= dp[m+1-p][n-q]:
                        if m-p < n-q :
 #                           print('add - to cp1:',m+1-p)
                            ##copy11.pop(0)
                            copy11.insert(m+1-p,'-')
 #                           print(copy11,copy22,'after add - to cp1')  
                        else:
 #                           print('edit cp1 at:',m-p,copy11[m-p],'to cp2 at ',n-q,copy22[n-q])
                            copy11[m-p] = copy22[n-q]
 #                           print(copy11,copy22,'after change')  
                            Q = q + 1
                            flag = 0
                            break 

                    elif dp[m-p][n+1-q] >= dp[m-p][n-q] and dp[m+1-p][n-q] >= dp[m-p][n-q]:
  #                      print('edit cp1 at:',m-p,copy11[m-p],'to cp2 at ',n-q,copy22[n-q])
                        copy11[m-p] = copy22[n-q]
  #                      print(copy11,copy22,'after change')  
                        Q = q + 1
                        flag = 0
                        break  

    return [copy11,copy22]  # 返回将整个s1转换成s2的最小编辑距离


In [262]:
s1 ="EYPTTPIWFDQWIPCQSIKEWTINYWNSAPFGLMFVGYSYYAYWAHPCFYKWTIGPQIDKLISTCAHAFGFSMYHYGAEGFVLGEMMLETTYKMLLNKHVNQFHIDDSFDCINPIAHHRMVLSHNFCMHDVLEHYYNLSEDNWFAMFAYDYLRMIEMCIWGVTTCDCSDHYFKPPAIHQCYQMARWFIDTYASRICIYNARDNEFPMQPIVMRFCMDQIHFGTDMRCHCEANEYPGFEGNQGEKWWRQLKYMMQQATLAIHCCYLAQHTFGLFEGDFLLEMPINLCQTHTRELQRWSNSYQLHTHVFHKMSDHLVCTHKKVPCLVALKDHIDIMWTCIYWGEHVTITMKRSHPHMPVLGYHLVDRECVNAWHWESMPCQNVMYLYNSKTFWCSTAGQNYNDWNCNSYPSRTCGPAMHPFEQGVRHTKSNICYRYHNMQTTPIVEAGAFCGPWAEPEKSQGNFRLKCHADTGDNIRIQQYVENLWKHSTLKEPCESYENIYNGVPFEYMEPFLYVECWRNKIIAVAKRVAQIDDQGGNADHVCWQPDPNCLYDTLCMWGRCLAGLQFKIPEWCVRATPTPYPCNRKAGQRGSDFWQKGMLQLQPGEYWDGVQGNNTISSSRTMREPQVKNWLQEFGPKHMQAPQRGWHRIPAQSHQVDCGCCIFDDTHAIYNQPSCEKFRRKKQQNCRLLGKIFDQDQRNWHPDIRAAPVKAVDDLGQDHPAWQPNKDMYFWCSMISAECEPVLTQIQVYDGRPMTKEGRDSHKEGQWEYERSHALKSKHQIFTEAMNSIQVNRCMMPR"
s2="EYPTTPIWFDPELAQEWYKWIINCFKEPCPFGLMFVWAHPCDSYKWYIGPEAVIDKWQAMKMKWRCAHAYGAEGFKLGELMLETTYKMLNNCSSNMEFKHVNCFHIDDSFDCINPIAHHRMVLSHNFCMHDVLEHYYWILSEDDYLRMIEMTWWALEQIWGVTHNVQFLGMYDLRIKPEIHRWFIDTYASRICIYNARDNEFPMQPIVMRFCMDQIHTDMRCHPHAYEYFGFEFECITGNQGLAIYCCYLAQHTFGLFINDFLLEMPINLAYCQTHHRELDRESNSYQLHTHVFHKMYPHTTGIHLWFTHKKEIWVSSKLPCLVALKTHIFAHWWLKHMWTCIYWGEHVTITMYHSHPHLPVWGYHLVDTEATMDPVTQACVNAESMPCQPVWYLYLSKTFGQNYNDWNCNSYPSRTCGPAMVPFEQGVRHTKSNICYRYHNMNTTPIVEAGAFCIRWAEEPPHLKCHADTGDNIWLQQYVENLWKHDTLKEPCESYENYYNGVPFEYKEPFAGGNADHVCWVVPDPEIMNCLEDTTCMWGMTPVQDECLEGLQDFKIRNWCIRATPTYYPPNRHAGQRFWQKGMLQLQPGEYEDGVQGNNTISSSCSEEQREYTQREPQVKNWLQECGPKHCQAPQRGWHRIPAQSHQVFSNELDDTIAYNQPSEKFCRFLGKIFNIDQDIRAKAVDDLGNDDPAWQPNKDMYWCSKISAECDPVLTQIQVYDGRPDTKEGRDTHYRSHALKSMHQIFTGAMRSIQVNRCLMPR"
with open(r"D:\downloads\rosalind_edta.txt",'r+') as file:
    fr = file.readlines()
print(fr)
refi = []
for line in range(len(fr)):
    if '>' in fr[line]:
        refi.append(',')
    else:
        refi.append(fr[line])
input1 = ''.join(refi).replace('\n','').split(',')[1]
input2 = ''.join(refi).replace('\n','').split(',')[2]



['>Rosalind_2159\n', 'ILSNNGGCIVSSIVYANSGPRWEKHQKAVTACGGWICIKNNVSKMCLSVKIESVTNFTAH\n', 'GDNYRKYCNEMFTSPSIKWRPHPRVGTWFPLSFKYMWKQIWEYPDIHRNFLFCFQTFVAF\n', 'IVCIHIECGYPECQPAAKAIQTEMKPKPYKDRQSHKFHTNNSLEYNQFTKKMSKGTYTWV\n', 'TYYEEEQLWVGRLYKRVKKCKWGEKKWANYQWTKGWHWVDWDGDSYPCQRSSSTQSTQPN\n', 'PNERPAWSNAGMEFGLTSDLHGGNEYFGKSTDWVIHGLCQQTGLWWFKDVTNWGFWYHSL\n', 'WFNVRKRDIMHPSVEIAYAAWTCSFVIARSLLCLTHDRECITCRLKWRANEGRIMMNCAL\n', 'FAWNNPMHKWNYQQRSSDPCVTNYGSDKKFSMHAVYICKCMTETTEHSSSAKFAQQPRFD\n', 'CSRAEADSKRTLTKGWEAMPWVEQIAFYVVTWIPQTLAFTYFTAMLGGSPMWTVGFPTMS\n', 'FAAQSQYSCQQEDGCATFMLKEQGTAHPHKAKTGQGWSMIAHAVFVEGNPMMYYNWIPHR\n', 'PPGLWLAYPCNGIDKQPAPLSFEINNHLGCGHPFISATSKGDECCTGTIWTWQNPCDGQK\n', 'NSTEGFNNNFDWCNTMIDGCHEGMLMLKIWPIWMMLEFCVGGASRMISHMVACSDQRPTF\n', 'HQCHNMACEVAWFWQFGSNYKDPPVIGWSPDGECSTTLQVYKENFWGGPQTTAVDLPENP\n', 'FESQMHHLEFMGHLKILWLPPPIEWPLDMHSRMGIIHFTNMLR\n', '>Rosalind_1671\n', 'ILSGNGLCINHQKAVTACSTNGWIADWIRSSICKEQRINVSKMCESVNIESVTNFTANGD\n', 'NYRDGGGQAVQAYCNMSPSRVGIHFEIYEYPDIHRNFLFCFQTFVAFIVCI

In [ ]:
print("Alignment后的字符串1:", ''.join(edit_distance_allignment(input1,input2,DP)[0]))
print("Alignment后的字符串2:", ''.join(edit_distance_allignment(input1,input2,DP)[1]))

#进一步考虑获取全解
6*7 m<n  forward：right, diag;   back:left,diag

|       |     | P | R| T | T | E | I | N |  
|       | 0  | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 
| P	| 1  | 0 | 1 | 2 | 3 | 4 | 5 | 6 |  	
| R	| 2  | 1 | 0 | 1 | 2 | 3 | 4 | 5 |  	
| E    | 3  | 2 | 1 | 1 | 1 | 2 | 3 | 4 | 	
| T	| 4  | 3 | 2 | 1 | 1 | 2 | 3 | 4 |  	
| T	| 5  | 4 | 3 | 2 | 1 | 2 | 3 | 4 |  	
| Y	| 6  | 5 | 4 | 3 | 2 | 2 | 3 | 4 |  	

同样的最小距离 4
0    (1,1)   (1,1)   (1,1)   (1,1)   (1,1)   (1,1)    ...  
0    (2,2)   (2,2)   (2,2)   (2,2)   (2,2)   (2,2)    
1    (3,3)   (3,3)   (3,3)   (3,2)   (3,2)   (3,2)   
1    (4,4)   (4,4)   (4,4)   (4,3)   (4,3)   (4,3)   
2    (5,5)   (5,5)   (4,5)   (5,4)   (5,4)   (5,4)  
3    (6,6)   (5,6)   (6,6)   (6,5)   (5,5)   (5,5)   
4    (6,7)   (6,7)   (6,7)   (6,6)   (5,6)   (6,6)   
4     /          /        /        (6,7)   (6,7)   (6,7) 

P R T<->E T E<->T I<->Y N<->-
PRTTEIN PRETTY-
P R T<->E T E<->T I<->- N<->T
PRTTEIN PRETT-Y
P R T<->E T E<->-  I<->T N<->Y
PRTTEIN PRET-TY

P R -<->E T T E<->Y I<->- N<->-         答案选择的
PR-TTEIN PRETTY--
P R -<->E T T E<->- I<->- N<->Y
PR-TTEIN PRETT--Y
P R -<->E T T E<->- I<->Y N<->-
PR-TTEIN PRETT-Y-

|       |     | P | R| T | T | E | I | N |  
|       | 0  | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 
| P	| 1  | 0 | 1 | 2 | 3 | 4 | 5 | 6 |  	
| R	| 2  | 1 | 0 | 1 | 2 | 3 | 4 | 5 |  	
| E    | 3  | 2 | 1 | 1 | 1 | 2 | 3 | 4 | 	
| T	| 4  | 3 | 2 | 1 | 1 | 2 | 3 | 4 |  	
| T	| 5  | 4 | 3 | 2 | 1 | 2 | 3 | 4 |  	
| Y	| 6  | 5 | 4 | 3 | 2 | 2 | 3 | 4 |  	
以下有一些编辑距离（5）不最小的反例
0    (1,1)   (1,1)     ...  
0    (2,2)   (2,2)   
1    (2,3)   (3,3)   
1    (3,4)   (4,4)  
1      \       (5,4)  
2    (4,5)   (6,5)  
3    (5,6)   (6,6)   
4    (6,7)   (6,7)  

P R T<->E T E<->-  I<->T N<->Y
PRTTEIN PR-ETTY

P R T<->E -<->T T E<->Y I<->- N<->-
PRT-TEIN PRETTY--

...



In [261]:
input1 = s1
input2 = s2


In [86]:
input1 = "horse"
input2 = "ros"

In [87]:
input1 = "PRETTY"
input2 = "PRTTEIN"

In [88]:
DP = edit_distance(input1,input2)[1]
print("最小编辑距离:", edit_distance(input1,input2)[0])
print("动态规划矩阵：\n",np.array(DP).reshape(len(input1)+1,len(input2)+1))

最小编辑距离: 4
动态规划矩阵：
 [[0 1 2 3 4 5 6 7]
 [1 0 1 2 3 4 5 6]
 [2 1 0 1 2 3 4 5]
 [3 2 1 1 2 2 3 4]
 [4 3 2 1 1 2 3 4]
 [5 4 3 2 1 2 3 4]
 [6 5 4 3 2 2 3 4]]


In [89]:
def edit_alignment(v, w):
    '''Returns the edit score and edit alignment of strings v and w.'''
    import numpy as np

    # Initialize the matrices.
    S = np.zeros((len(v)+1, len(w)+1), dtype=int)
    backtrack = np.zeros((len(v)+1, len(w)+1), dtype=int)

    for i in range(1, len(v)+1):
        S[i][0] = i
    for j in range(1, len(w)+1):
        S[0][j] = j

    # Fill in the Score and Backtrack matrices.
    for i in range(1, len(v)+1):
        for j in range(1, len(w)+1):
            scores = [S[i-1][j-1] + (v[i-1] != w[j-1]), #identical(+0)/change(+1)
                      S[i-1][j]+1,                      #w.insert(j,'-'),add col (to word2) or del row (to word1)
                      S[i][j-1]+1]                      #v.insert(i,'-'),add row or del col
            S[i][j] = min(scores)
            backtrack[i][j] = np.argmin(scores) # scores.index(S[i][j]) 0,1,2
    print(S)
    print(backtrack)

    ## Quick lambda function to insert indels.
    #insert_indel = lambda word, i: word[:i] + '-' + word[i:]

    # Initialize the aligned strings as the input strings.
    v_aligned, w_aligned = v, w
    vl,wl = list(v_aligned),list(w_aligned)

    # Initialize the values of i,j and get the minimum score.
    i,j = len(v), len(w)
    min_score = S[i][j]

    # Backtrack to the edge of the matrix starting bottom right.
    while i*j != 0:
        if backtrack[i][j] == 1:
            i -= 1
            # w_aligned = insert_indel(w_aligned, j)
            wl.insert(j,'-')
            print('add - to l2 at ', j+1)
        elif backtrack[i][j] == 2:
            j -= 1
            # v_aligned = insert_indel(v_aligned, i)
            vl.insert(i,'-')            
            print('add - to l1 at ', i+1)
        else:
            i -= 1
            j -= 1

    # Prepend the necessary preceeding indels to get to (0,0).
    for _ in range(i):
        #w_aligned = insert_indel(w_aligned, 0)
        wl.insert(0,'-')
    for _ in range(j):
        #v_aligned = insert_indel(v_aligned, 0)
        vl.insert(0,'-')
    return str(min_score), ''.join(vl),''.join(wl) #v_aligned, w_aligned

if __name__ == '__main__':

    # Get the edit alignment.
    edited = edit_alignment(input1, input2)

    # Print and save the answer.
    print ('\n'.join(edited))

[[0 1 2 3 4 5 6 7]
 [1 0 1 2 3 4 5 6]
 [2 1 0 1 2 3 4 5]
 [3 2 1 1 2 2 3 4]
 [4 3 2 1 1 2 3 4]
 [5 4 3 2 1 2 3 4]
 [6 5 4 3 2 2 3 4]]
[[0 0 0 0 0 0 0 0]
 [0 0 2 2 2 2 2 2]
 [0 1 0 2 2 2 2 2]
 [0 1 1 0 0 0 2 2]
 [0 1 1 0 0 2 0 0]
 [0 1 1 0 0 0 0 0]
 [0 1 1 1 1 0 0 0]]
add - to l1 at  5
4
PRET-TY
PRTTEIN


In [252]:
def move(node,row,col,wl,vl,nindex):
    print('current node ', node)
    n1 = list(nindex[1])
    n2 = list(nindex[2])
    n0 = list(nindex[0])
    print('current node1 index ', n1)
    print('current node2 index ', n2)
    print('current node0 index ', n0)
    if node[1] == 1:
            row -= 1
            wl.insert(col,'-')
            print('add - to l2 at ', col+1)
            #list(nindex[1]).remove([1,row,col])
            n1.pop(n1.index([1,row,col]))
    elif node[2]== 1:
            col -= 1
            vl.insert(row,'-')            
            print('add - to l1 at ', row+1)
            #list(nindex[2]).remove([2,row,col])
            n2.pop(n2.index([2,row,col]))
    elif node[0] == 1:
            row -= 1
            col -= 1  
            #list(nindex[0]).remove([0,row,col])
            n0.pop(n0.index([0,row,col]))
    return node,row,col,wl,vl,nindex

def edit_alignment(v, w):
    '''Returns the edit score and edit alignment of strings v and w.
       S for edit distance
       backdir for direction
       nodindex for location
    '''
    import numpy as np

    # Initialize the matrices.
    S = np.zeros((len(v)+1, len(w)+1), dtype=int)
    backdir = [np.zeros((len(v)+1, len(w)+1), dtype=int),np.zeros((len(v)+1, len(w)+1), dtype=int),np.zeros((len(v)+1, len(w)+1), dtype=int)]  #expand to 3 dim

    for i in range(1, len(v)+1):
        S[i][0] = i
    for j in range(1, len(w)+1):
        S[0][j] = j

    # Fill in the Score and Backtrack matrices.
    for i in range(1, len(v)+1):
        for j in range(1, len(w)+1):
            scores = [S[i-1][j-1] + (v[i-1] != w[j-1]), #identical(+0)/change(+1)
                      S[i-1][j]+1,                      #w.insert(j,'-')
                      S[i][j-1]+1]                      #v.insert(i,'-')
            S[i][j] = min(scores)
            #backtrack[i][j] = np.argmin(scores) # scores.index(S[i][j]) 0,1,2
            if min(scores) == max(scores):
                #[backdir[_][i][j]=1 for _ in range(len(scores))]
                for _ in range(len(scores)):
                    backdir[_][i][j]=1
            else:
                #[backdir[_][i][j]=1 for _ in list(range(len(scores))) if scores[_] == min(scores)]
                for _ in list(range(len(scores))): 
                    if scores[_] == min(scores):
                        backdir[_][i][j]=1 
    print(S)
    print(backdir)

    ## Quick lambda function to insert indels.
    #insert_indel = lambda word, i: word[:i] + '-' + word[i:]

    # Initialize the aligned strings as the input strings.
    v_aligned, w_aligned = v, w
    vl,wl = list(v_aligned),list(w_aligned)

    # Initialize the values of i,j and get the minimum score.
    i,j = len(v), len(w)
    min_score = S[i][j]

    # Backtrack to the edge of the matrix starting bottom right.
    flag = 1

    print(np.shape(backdir))
    index11 = np.zeros(np.shape(backdir[0]))
    index2 = np.repeat(range(j+1),i+1).reshape(i+1,j+1) #col
    index3 = np.repeat(range(i+1),j+1).transpose().reshape(np.shape(backdir[0])) #row
    index21 = np.ones(np.shape(backdir[0])) #(i,j)
    index31 = np.repeat(np.repeat(2,j+1),i+1).reshape(np.shape(backdir[0])) 
    #nindex = [np.repeat(np.repeat([[],[],[]],j+1),i+1),np.repeat(np.repeat([[],[],[]],j+1),i+1),np.repeat(np.repeat([[],[],[]],j+1),i+1)]
    #nindex = [np.repeat(np.repeat(['0','0','0'],j+1),i+1),np.repeat(np.repeat(['0','0','0'],j+1),i+1),np.repeat(np.repeat(['0','0','0'],j+1),i+1)]
    nindex0 = []
    nindex1 = []
    nindex2 = []    
#    print(nindex)
#    print(np.shape(nindex))
    for r in range(i+1):
        print('element of nindex0 ',list(zip(index11[r],index2[r],index3[r])),' at row ',r)
        nindex0.append(list(zip(index11[r],index2[r],index3[r])))
        nindex1.append(list(zip(index21[r],index2[r],index3[r])))
        nindex2.append(list(zip(index31[r],index2[r],index3[r])))

    nindex = [np.array(nindex0,dtype = int),np.array(nindex1,dtype = int),np.array(nindex2,dtype = int)]  
    #print('input nodes index：',nindex) #[0,x,y],[1,x,y],[2,x,y]
    print('input node0 index：',nindex[0]) #[0,x,y]
    print('input node1 index：',nindex[1]) #[0,x,y]
    print('input node2 index：',nindex[2]) #[0,x,y]
    
    nn = len(nindex)
    print(nn,' nodes in all')
    Allignments = []
    while nn >0:
        while i*j!= 0:
            print(i,j)
            print(backdir[0][i][j],backdir[1][i][j],backdir[2][i][j]) 
            #if np.sum(backdir[:][i][j],0) == 1:
            if backdir[0][i][j]+backdir[1][i][j]+backdir[2][i][j]== 1:
                nindex[0].remove(backdir[0][i][j])
                nindex[1].remove(backdir[1][i][j])
                nindex[2].remove(backdir[2][i][j])
                if backdir[1][i][j] == 1:
                    i -= 1
                    # w_aligned = insert_indel(w_aligned, j)
                    wl.insert(j,'-')
                    print('add - to l2 at ', j+1)
                elif backdir[2][i][j] == 1:
                    j -= 1
                    # v_aligned = insert_indel(v_aligned, i)
                    vl.insert(i,'-')            
                    print('add - to l1 at ', i+1)
                elif backdir[0][i][j] == 1:
                    i -= 1
                    j -= 1               
            else:
                _,row,col,wl,vl,nindex = move([backdir[0][i][j],backdir[1][i][j],backdir[2][i][j]],i,j,wl,vl,nindex)

        # Prepend the necessary preceeding indels to get to (0,0).
        for _ in range(row):
            #w_aligned = insert_indel(w_aligned, 0)
            wl.insert(0,'-')
        for _ in range(col):
            #v_aligned = insert_indel(v_aligned, 0)
            vl.insert(0,'-')
        if [''.join(vl),''.join(wl)] not in Allignments:
            Allignments.append([''.join(vl),''.join(wl)])
        nn = len(nindex)

    return str(min_score), ''.join(vl),''.join(wl) #v_aligned, w_aligned

if __name__ == '__main__':
    # Get the edit alignment.
    edited = edit_alignment(input1, input2)

    # Print and save the answer.
    print ('\n'.join(edited))

[[0 1 2 3 4 5 6 7]
 [1 0 1 2 3 4 5 6]
 [2 1 0 1 2 3 4 5]
 [3 2 1 1 2 2 3 4]
 [4 3 2 1 1 2 3 4]
 [5 4 3 2 1 2 3 4]
 [6 5 4 3 2 2 3 4]]
[array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 1, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1]]), array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 0]]), array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1]])]
(3, 7, 8)
element of nindex0  [(np.float64(0.0), np.int64(0), np.int64(0)), (np.float64(0.0), np.int64(0), np.int64(0)), (np.float64(0.0), np.int64(0), np.int64(0)), 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [263]:

  def findmin(t1, t2, t3):
    '''    返回上、左和对角线这三个单元格走哪个经历的编辑次数最少
    :param t1, t2, t3: 对角、上、左三个单元格
    :return: 编辑距离最小的单元格
    '''
    if t1[1] <= t2[1] and t1[1] <= t3[1]:
        return t1
    if t2[1] < t1[1] and t2[1] < t3[1]:
        return t2
    if t3[1] <= t2[1] and t3[1] < t1[1]:
        return t3


def EDTA(s1, s2):
    '''用动态规划法进行两个序列的比对'''

    # 从这里开始进行动态规划矩阵的定义和填充
    m, n = len(s1), len(s2)
    dp = [[['', 0] for j in list(range(n + 2))] for i in list(range(m + 2))] # 定义空的动态规划矩阵
    dp[1][0][0] = '-'
    dp[0][1][0] = '-' # 把空位放进空矩阵的最开始

    # 下面的两个for循环把待比对的两个序列分别放进矩阵的第一列和第一行，并初始化空位罚分
    for i in list(range(2, m + 2)):
        dp[i][0][0] = s1[i - 2]
        dp[i][1][1] = i - 1
        dp[i][1][0] = '↑';
    for j in list(range(2, n + 2)):
        dp[0][j][0] = s2[j - 2]
        dp[1][j][1] = j - 1
        dp[1][j][0] = '←';

    # 在下面的for循环嵌套中实现矩阵的填充
    for i in list(range(2, m + 2)):
        for j in list(range(2, n + 2)):
            if dp[i][0][0] == dp[0][j][0]: # 如果两字符匹配
                tep1 = ['↖', dp[i - 1][j - 1][1]] # 不增加空格则不需要增加编辑次数
                tep2 = ['←', dp[i][j - 1][1] + 1] # 增加空位则需要给编辑次数加一
                tep3 = ['↑', dp[i - 1][j][1] + 1]

                dp[i][j] = findmin(tep1, tep2, tep3) # 用使编辑次数最小的方式填充此单元格

            else: # 如果两字符不匹配
                tep1 = ['↖', dp[i - 1][j - 1][1] + 1] # 不增加空格则相当于错配，编辑次数增加一
                tep2 = ['←', dp[i][j - 1][1] + 1] # 增加空位则需要给编辑次数加一
                tep3 = ['↑', dp[i - 1][j][1] + 1]
                dp[i][j] = findmin(tep1, tep2, tep3) # 用使编辑次数最小的方式填充此单元格

    # 从这里开始进行最小编辑次数的回溯
    s3 = []
    s4 = [] # 用s3和s4接收回溯得到的比对序列
    i = m + 1
    j = n + 1 # 从矩阵的右下角开始向左上方回溯
    while i > 1 or j > 1:
        if dp[i][j][0] == '↖': # 如果遇到↖符号
            s3.append(dp[i][0][0])
            s4.append(dp[0][j][0]) # 则分别把这两个比对上的字符加到两个比对序列中
            i -= 1
            j -= 1 # 沿对角线向左上方移动一格
        elif dp[i][j][0] == '←': # 如果遇到&#39;←&#39;符号
            s4.append(dp[0][j][0]) # 把横向放置的序列对应字符放入s4
            s3.append('-') # 给s3中添加一个空位
            j -= 1 # 向左移一格
        elif dp[i][j][0] == '↑': # 如果遇到&#39;↑&#39;符号
            s4.append('-') # 给s4中添加一个空位
            s3.append(dp[i][0][0]) # 把纵向放置的序列对应字符放入s3
            i -= 1 # 向上移一格
    s3 = s3[::-1]
    s4 = s4[::-1] # 把s3、s4倒序
    return s3,s4

seq1 = input1
seq2 = input2
[s3, s4] = EDTA(seq1, seq2)

o1 = ''.join(s3)
o2 = ''.join(s4) # 把列表转为字符串，方便输出


num = 0 # 统计两条比对后的序列有多少不一样的字符
for i in range(len(o1)):
    if o1[i] != o2[i]:
        num += 1

print(str(num))
print(o1)
print(o2)


391
ILSNNGGCI-VSSIVYANSGPRWEKHQKAVTACGGWICIKNNVSKMCLSVKIESVTNFTAHGDNYRKYCNEMFTSPSIKWRPHPRVGTWFPLSFKYMWKQIWEYPDIHRNFLFCFQTFVAFIVCIHIECGY----PECQPAAKAIQTEMKPK-PYKDRQSHKFHTNNS--------LEYNQFT--KKMSKGTYTWVTYYEEE-QLWVGRLYKRVKKCKWGEKKWANYQ-------WTKGWH-----WVDW-DGDSYPCQRSSSTQSTQPNP-N--E--RPAWS-NAGMEFGLTSDLHGGNEYFGKSTDWVIHGLCQQTGLWWFK--DVTNWGFWYHSLWFNVRKRDIMHPSVEIAYAAWTCSFVIARSLLCL-------T-HDR-------E-CITCRLKWRANEGRIMMNCALFAWNNPMH----KWNYQQRSSDPCVTNYGSDKKFSMHAVYICKCMTETTEHSSSAKFAQQPRFDCSRAEADSKRTLTKGWEAMPWVEQIAFYV-VTWIPQ-T--LAFTYFTAMLGGSPMWT----VGFPT---MSFAAQSQYSCQQEDGCATFM-LK-EQGTAHPHKAKTGQGWSMIAHAVFVEGNPMMYYNWIPHRPPGLWLAYPCNGIDKQPAPLSFEINNHLGCGHPFISATSKGD-ECCTGTIWTWQNPCDGQKNSTEGFNNNFDWCNTMIDGCHEGMLM-------LK-IW-PIWMMLEFCV-GGASRMISHMVACSDQ---R--PTFHQCHNMACEVAWFWQFGSNYKDPPVIGWSPDGECSTTLQVYKENFWGGPQTTAVDLPENPFE---S--QMHHLEFMGHLKILWLPPPIEWPLDMHSRMGIIHFTNM---LR
ILSGNGLCINHQKAVTACSTNGWIADWIRSSIC-KEQRI--NVSKMCESVNIESVTNFTANGDNYR-DGGGQAVQAYCNMSP-SRVG----IHF-----EIYEYPDIHRNFLFCFQTFVAFIVCIHIECGYGFRQME

In [ ]:
DP = edit_distance(input1,input2)[1]
print("最小编辑距离:", edit_distance(input1,input2)[0])
print("动态规划矩阵：\n",np.array(DP).reshape(len(input1)+1,len(input2)+1))

#for awns in edit_distance_allignment_all(input1,input2,DP):
AWN = edit_distance_allignment_all(input1,input2,DP)
for awns in AWN:
    print("Alignment后的字符串1:", awns[0])
    print("Alignment后的字符串2:", awns[1])

最小编辑距离: 454
动态规划矩阵：
 [[  0   1   2 ... 947 948 949]
 [  1   0   1 ... 946 947 948]
 [  2   1   0 ... 945 946 947]
 ...
 [856 855 854 ... 454 455 456]
 [857 856 855 ... 455 454 455]
 [858 857 856 ... 456 455 454]]


NameError: name 'edit_distance_allignment_all' is not defined

In [ ]:
s1 ="LRTNLPVYLYNWVKIDVYHHTGAKFPYLKEEAQCRNRNPNQCYHRAISHGGTHPFRTTHMYDENRMHTIIHNNCWAKTRQWFKPETYLWVQAWNKIIPWTKKELEMQWKDIGLPFGPPKIFSFFPRWITMYVTTEINCLDGNYGQNKLMNPTPAEWCPPIFRLMPINVQRSPLVTMRCWDTHDMANLNRIMVSKLVHSISMTQKVFKCMLPLTTQTECCYRPESQEYNKMQAKYNMEANGSSMATQKVRRKWDDTSCYQHFEVCGKIQCAYDVSVSSIPFPEWRFNGEWIVGWDENNHPFMKFHLTHYKTGACLQGQKWSIAPATYASCGRENEAGGMQFIASRLAFRFTGRETTFVRDFGACYRQAKIHAVIIYEYSGILRDVSQMRDGDFFTSHSMKYKAYHRDRMLQEWVMHGRMSTPGQNFHGKEPSSVNEMSKQKYANCPWFWNAEVLFMGCFFTWWPFHKVIPSGDSQDDRCLEGDWCKVIPEVSSKAGWWHRTTMWMTAEPCKMFALFKYVKPEEANSFAPSQDVFACPFVNVTIFMKKFFYKDFIVCDLMDDTQSGMHKTGRFKAFFCHHDNKYGTLSMHSMFIRAQFWHGHWIDTSGRTRNSMTGNWWFTHKYFKSMNRCGHAGECPIPEVPDHDYPVRHICYWQKRLKEVYDPPGEGQIQPIVFRGWYYYFRIGSSDGFYSHCITKVNKFRSKLRYWGKLHLTQAFEADMWCAEMCENLKAWDKHPVFTRWCSESRPHMTDQSTLA"
s2 = "LRTNLPVYVYHHTPCKDQNCVQTKMEAQRINCQMHVMKNWQHRAISHGMHHNQCWAKTRQWEKPETYLWQQPQAWSTRRPPNEIIPSHKKELEMQWKDIVLPFGPPKIFSFFPRWITRTLDYQMNNCLDGNYGQMKLMLFPTPGQDGTVEWPPIFRIMPINVTGAMARSPLLTMRCWDTPQQMVSKLVHSISMTQKVFKCMLPLTTQYCGQYTPTWAYACDCIYRPESQHYNSMQAKMLTDPPENNEANGSSMATQKCRHKWDDTSCYQFFFVCGKIAAIEEHRVAHDVSIFHPSSIPFPEWRFNGENEIVGWDENNHPFMKTHYTWREYRYKTRAWLQGAETQLGTTATYVDNGISHACGRCNSAGGMQFIRSRLAFRFTRKDCGSREVRDFGACYRQAKIIMIAIRWVIYEIWRDVSQMRDGSFFTSHCTRETWTTYKAYHRDQEWVGYEVSYHGRMSTPGENFHGPEPSSIRWMATCNEMSCNAEVLTCNTCHIKAHGCFFCNRGKVCSGCYQLGRFNITQDDRCPEVSSWHRTTMWMTAEPCKMFALFKYVKPEEANSFAQDVFVCPFKKFFYKDFIFCDLDDTQSCHMHKTGRFKAFQRECHEVKEQDDNKYGTLSFFIRFWHGHWGRNKFDCDWDRINLWNCPLTSIAQYMTGNWKFTQKYFKRMNRCVHASGVPWLQLPEVPDHDYPVVCISDRMDHNCYNQKRLKPVYDPPGENPFWMRGFMSRRWRDCWFTHPVAYTYSYIALNRSSDGRYSHCIKLRYWGKMPHLRWAFEADMTDIFCAEMCENLKAWDKHPDMSTHIVLMHTHA"
DP = edit_distance(s1,s2)[1]

In [ ]:
s1 ="LRTNLPVYLYNWVKIDVYHHTGAKFPYLKEEAQCRNRNPNQCYHRAISHGGTHPFRTTHMYDENRMHTIIHNNCWAKTRQWFKPETYLWVQAWNKIIPWTKKELEMQWKDIGLPFGPPKIFSFFPRWITMYVTTEINCLDGNYGQNKLMNPTPAEWCPPIFRLMPINVQRSPLVTMRCWDTHDMANLNRIMVSKLVHSISMTQKVFKCMLPLTTQTECCYRPESQEYNKMQAKYNMEANGSSMATQKVRRKWDDTSCYQHFEVCGKIQCAYDVSVSSIPFPEWRFNGEWIVGWDENNHPFMKFHLTHYKTGACLQGQKWSIAPATYASCGRENEAGGMQFIASRLAFRFTGRETTFVRDFGACYRQAKIHAVIIYEYSGILRDVSQMRDGDFFTSHSMKYKAYHRDRMLQEWVMHGRMSTPGQNFHGKEPSSVNEMSKQKYANCPWFWNAEVLFMGCFFTWWPFHKVIPSGDSQDDRCLEGDWCKVIPEVSSKAGWWHRTTMWMTAEPCKMFALFKYVKPEEANSFAPSQDVFACPFVNVTIFMKKFFYKDFIVCDLMDDTQSGMHKTGRFKAFFCHHDNKYGTLSMHSMFIRAQFWHGHWIDTSGRTRNSMTGNWWFTHKYFKSMNRCGHAGECPIPEVPDHDYPVRHICYWQKRLKEVYDPPGEGQIQPIVFRGWYYYFRIGSSDGFYSHCITKVNKFRSKLRYWGKLHLTQAFEADMWCAEMCENLKAWDKHPVFTRWCSESRPHMTDQSTLA"
s2 = "LRTNLPVYVYHHTPCKDQNCVQTKMEAQRINCQMHVMKNWQHRAISHGMHHNQCWAKTRQWEKPETYLWQQPQAWSTRRPPNEIIPSHKKELEMQWKDIVLPFGPPKIFSFFPRWITRTLDYQMNNCLDGNYGQMKLMLFPTPGQDGTVEWPPIFRIMPINVTGAMARSPLLTMRCWDTPQQMVSKLVHSISMTQKVFKCMLPLTTQYCGQYTPTWAYACDCIYRPESQHYNSMQAKMLTDPPENNEANGSSMATQKCRHKWDDTSCYQFFFVCGKIAAIEEHRVAHDVSIFHPSSIPFPEWRFNGENEIVGWDENNHPFMKTHYTWREYRYKTRAWLQGAETQLGTTATYVDNGISHACGRCNSAGGMQFIRSRLAFRFTRKDCGSREVRDFGACYRQAKIIMIAIRWVIYEIWRDVSQMRDGSFFTSHCTRETWTTYKAYHRDQEWVGYEVSYHGRMSTPGENFHGPEPSSIRWMATCNEMSCNAEVLTCNTCHIKAHGCFFCNRGKVCSGCYQLGRFNITQDDRCPEVSSWHRTTMWMTAEPCKMFALFKYVKPEEANSFAQDVFVCPFKKFFYKDFIFCDLDDTQSCHMHKTGRFKAFQRECHEVKEQDDNKYGTLSFFIRFWHGHWGRNKFDCDWDRINLWNCPLTSIAQYMTGNWKFTQKYFKRMNRCVHASGVPWLQLPEVPDHDYPVVCISDRMDHNCYNQKRLKPVYDPPGENPFWMRGFMSRRWRDCWFTHPVAYTYSYIALNRSSDGRYSHCIKLRYWGKMPHLRWAFEADMTDIFCAEMCENLKAWDKHPDMSTHIVLMHTHA"
DP = edit_distance(s1,s2)[1]
print("Alignment后的字符串:", edit_distance_allignment(s1,s2,DP)[0], edit_distance_allignment(s1,s2,DP)[1])

Alignment后的字符串: ['L', 'R', 'T', 'N', 'L', 'P', 'V', 'Y', 'V', 'Y', 'H', 'H', 'T', 'P', 'C', 'K', 'D', 'Q', 'N', 'C', 'V', 'Q', 'T', 'K', 'M', 'E', 'A', 'Q', 'R', 'I', 'N', 'C', 'Q', 'M', 'H', 'V', 'M', 'K', 'N', 'W', 'Q', 'H', 'R', 'A', 'I', 'S', 'H', 'G', 'M', 'H', 'H', 'N', 'Q', 'C', 'W', 'A', 'K', 'T', 'R', 'Q', 'W', 'E', 'K', 'P', 'E', 'T', 'Y', 'L', 'W', 'Q', 'Q', 'P', 'Q', 'A', 'W', 'S', 'T', 'R', 'R', 'P', 'P', 'N', 'E', 'I', 'I', 'P', 'S', 'H', 'K', 'K', 'E', 'L', 'E', 'M', 'Q', 'W', 'K', 'D', 'I', 'V', 'L', 'P', 'F', 'G', 'P', 'P', 'K', 'I', 'F', 'S', 'F', 'F', 'P', 'R', 'W', 'I', 'T', 'R', 'T', 'L', 'D', 'Y', 'Q', 'M', 'N', 'N', 'C', 'L', 'D', 'G', 'N', 'Y', 'G', 'Q', 'M', 'K', 'L', 'M', 'L', 'F', 'P', 'T', 'P', 'G', 'Q', 'D', 'G', 'T', 'V', 'E', 'W', 'P', 'P', 'I', 'F', 'R', 'I', 'M', 'P', 'I', 'N', 'V', 'T', 'G', 'A', 'M', 'A', 'R', 'S', 'P', 'L', 'L', 'T', 'M', 'R', 'C', 'W', 'D', 'T', 'P', 'Q', 'Q', 'M', 'V', 'S', 'K', 'L', 'V', 'H', 'S', 'I', 'S', 'M', 'T', 'Q', 'K', 'V'

In [229]:
import numpy as np
print(np.argmin([6,2,3,4,5]))
t1 = 'pretty'
t2 = 'prttein'
at1 = np.array(t1)
at2 = np.array(t2)
print(list(t1).pop(1))
del(list(t1)[3])
print(list(t1))
ll = list(t1)
del(ll[3])
print(ll)
print(list(range(1,4)))
print(list(range(4,1,-1)))
print( '1' in ['1','o','B'],'1' in [1,'o','B'],1 in [1,'o','B'])
T = 2
print(list(range(T,4)))
print(''.join(['1','o','B']).replace('1',''))
l = [ll,[4,5],'b',['o','e']]
print(l)
l.insert(4,'A')
print(l)
B = [1,2,1]
print(B.index(2))
B.sort()
print(B)
A = ['1','2','1']
print(''.join(A).find('1'))
print(np.prod([[1,2],[1,2]]))
print(np.prod([[1,2],[1,2],[1,2]],0))
print(len([[],[],[]]))
print(np.size([[],[],[]]))
lll = [np.zeros((5,3)),np.zeros((5,3)),np.zeros((5,3))]
print(lll)
print(lll is False)
lll[0][2][2] = 1
lll[1][2][2] = 1
lll[2][4][2] = 1
lll[1][1][0] = 1
lll[0][1][0] = 1
lll[2][1][0] = 1
lll[0][1][2] = 1
lll[1][4][0] = 1
print(lll)
print(np.zeros(np.shape(lll[0])))
print(np.repeat(range(3),5).reshape(3,5).transpose())
print(np.repeat(range(5),3).transpose().reshape(np.shape(lll[0])))
print(np.array(list(zip(np.zeros(np.shape(lll[0])),np.repeat(range(3),5).reshape(3,5).transpose(),np.repeat(range(5),3).transpose().reshape(np.shape(lll[0]))))))
print(np.array(list(zip(np.zeros(np.shape(lll[0][0])),list(np.repeat(range(3),5).reshape(3,5).transpose())[0],list(np.repeat(range(5),3).transpose().reshape(np.shape(lll[0])))[0]))))


1
r
['p', 'r', 'e', 't', 't', 'y']
['p', 'r', 'e', 't', 'y']
[1, 2, 3]
[4, 3, 2]
True False True
[2, 3]
oB
[['p', 'r', 'e', 't', 'y'], [4, 5], 'b', ['o', 'e']]
[['p', 'r', 'e', 't', 'y'], [4, 5], 'b', ['o', 'e'], 'A']
1
[1, 1, 2]
0
4
[1 8]
3
0
[array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]]), array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]]), array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])]
False
[array([[0., 0., 0.],
       [1., 0., 1.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]]), array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [1., 0., 0.]]), array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]